/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CourseCard: typeof import('./src/components/CourseCard.vue')['default']
    CourseList: typeof import('./src/components/CourseList.vue')['default']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    HelperCollapse: typeof import('./src/components/HelperCollapse.vue')['default']
    KingArea: typeof import('./src/components/KingArea.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
